[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which of the following best describes ballot stuffing?
"""
prompt.distractors = [
    "Ballot harvesting, where individuals collect and submit ballots on behalf of others without their consent.",
    "Voter impersonation, where an individual votes using the identity of another eligible voter without their knowledge.",
    "Ballot box tampering, where sealed ballot boxes are illegally accessed and ballots are altered or replaced. ",
]
answer.answer = "The practice of submitting multiple ballots by a single individual in an election where one ballot per person is allowed."
id = "65448bbf-3caf-463a-8373-da96cea0c206"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
How can ballot stuffing occur in an election that a compromised VVPAT system?
"""
prompt.distractors = [
    "Voters themselves could engage in ballot stuffing by voting multiple times, through fake identity proof",
    "Voters could exploit a vulnerability in the VVPAT system where it fails to record a vote on EVM but still prints a paper trail, allowing them to cast multiple votes without detection.",
    "Election officials could replace legitimate VVPAT paper trails with fraudulent ones, inflating the vote count for a specific candidate.",
]
answer.answer = "VVPAT could print ballots while no voter is observing the paper trail."
context = """
VVPAT could print while no voter is observing the paper trail, a form of [ballot stuffing](https://en.wikipedia.org/wiki/Ballot_stuffing). Even if additional votes were discovered through matching to the voters list, it would be impossible to identify legitimate ballots from fraudulent ballots.
"""
id = "a1ae9861-25e2-49d4-88e2-2e283e4d0930"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Are VVPAT (Voter-Verified Paper Audit Trail) and EVM (Electronic Voting Machine) votes tallied after an election to ensure accuracy?
"""
prompt.distractors = [
    "Yes, all VVPAT and EVM votes are meticulously compared to identify any discrepancies.",
    "Yes, but only in close elections where the margin of victory is narrow.",
    "No, the VVPAT is solely for voter assurance and has no impact on the official count. ",
]
answer.answer = "No, only the votes from a random sample of VVPAT machines approximately 1% of VVPAT votes are compared with EVM results."
id = "2114e89b-8c80-4547-a18e-27a9a9092db6"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which statement best describes the impact of secrecy on software security?
"""
prompt.distractors = [
    "Secrecy enhances software security by preventing malicious actors from exploiting vulnerabilities.",
    "Secrecy fosters an environment of trust, as users perceive hidden mechanisms as more secure.",
    "Open-source software exposes code to a wider range of attackers, increasing the risk of exploitation.",
]
answer.answer = "Secrecy is a liability, as it hinders the identification and patching of security flaws by a wider community of experts."
context = """
Secrecy is a liability in software security. By keeping the software development process closed and secretive, it becomes more challenging to identify and address security vulnerabilities. A more effective approach is to embrace open-source development, where the source code is publicly available for review and contribution by a community of developers and security experts.
"""
id = "243aaeaa-4e7a-4187-a66e-f1153818a513"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Is the EVM (Electronic Voting Machine) system, including its components and software, open source and available for public audit by independent experts?
"""
prompt.distractors = [
    "Yes, the EVM system is entirely open source, allowing for full transparency and public scrutiny.",
    "The hardware components are open source, but the software remains closed-source and proprietary.",
    "While the software is open source, the hardware specifications are kept confidential. ",
]
answer.answer = "No, the EVM system is proprietary, and only authorized personnel have access to its inner workings."
id = "2573f0c4-1669-4c6d-bbdf-6b42ece47a61"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
How many days of security does an EVM require?
"""
prompt.distractors = [
    "60 days before and after election day",
    "30 days before the election",
    "365 days before the election",
]
answer.answer = "All the time"
context = """
EVMs demand protection for 365 days every year, whereas ballot papers need protection for only about few months, hardly 3-6 months after the election. Any unprotected EVM at any time is susceptible to hackers manipulating it and installing malware.It's unrealistic to have robust security for EVMs all the time.
"""
id = "48d771bd-143d-40fb-bead-1329f5d8d2f9"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
In how many constituency were discrepancies found between the number of voters polled on election day and the number of voters recorded in the EVMs during the vote-counting process in the 2024 Lok Sabha elections?
"""
prompt.distractors = [
    "An insignificant number of polling stations",
    "Less than half of the polling stations",
    "Less than one-third of the polling stations",
]
answer.answer = "Almost all polling stations"
context = """
Data of all discrepancies is here.

Only three constituencies have no discrepancies. (Amreli from Gujarat, Attingal from Kerala and Lakshadweep)

[Discrepancies EVM votes during polling and evm votes during counting](https://github.com/silicology/election_data_analysis/blob/main/data/voter_turnout_data/evm_turnout_matching/evm_voter_turnout_comparison.json)
"""
id = "72c3b0f6-72f3-40ca-b930-dbe4ae799bff"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which of the following statements is true regarding the impact of manipulating a single to three Electronic Voting Machine (EVM) in a constituency?
"""
prompt.distractors = [
    "It has little impact on the overall results as it is just one to three machine.",
    "The margin of victory is always substantial, so altering a few votes has no real consequence.",
    "The impact depends on the population density of the constituency, with urban areas being less affected.",
]
answer.answer = "It can be significant as many candidates win or lose by a narrow margin under the First Past the Post (FPTP) system."
context = """
In many democratic countries that employ the First Past the Post (FPTP) electoral system, elections are often decided by a small number of votes. Candidates frequently win or lose by margins of a few hundred or even fewer votes. In such scenarios, manipulating even a single EVM in a constituency can have a substantial impact. If an EVM is rigged to favor a particular candidate, it could potentially swing the result in their favor, especially in tightly contested races.
"""
id = "e263ddd2-7f06-46a9-a3c8-5003f6f86dac"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Why is a paper ballot considered more secure than an Electronic Voting Machine (EVM) in terms of manipulation? Which of the statements is correct?
"""
prompt.distractors = [
    "Paper ballots cannot be tampered with.",
    "With paper ballots, poll hacking is not possible, whereas with EVMs, it is possible due to their digital nature.",
    "Paper ballots can be destroyed, whereas EVMs are indestructible and resistant to fire and water",
]
answer.answer = "Evidence of paper ballot manipulation can be captured through CCTV or smartphone camera surveillance, while EVM manipulation occurs internally at the hardware and software levels, making it harder to detect."
context = """
Paper ballots allow for tangible evidence of manipulation, such as improper handling or ballot tampering, which can be documented through smartphone cameras, CCTV surveillance, or by physical inspection. This enables voters or observers to raise concerns and potentially call for a re-election. In contrast, EVMs operate digitally, and any manipulation within them typically involves hardware or software alterations inside the machine itself. This internal manipulation is not observable through external monitoring, making it much harder to detect and address potential fraud. Therefore, while both systems have vulnerabilities, paper ballots offer a transparent mechanism for identifying and addressing irregularities.
"""
id = ""
