[book]
title = "Iambrainstorming"
authors = ["Amiya Behera"]
language = "en"


[preprocessor.og-meta]
# Required: name of the binary (must be on PATH)
command = "mdbook-og-meta"

# Optional but recommended – builds og:url for every page
base_url = "https://iambrainstorming.vercel.app"

# Fallbacks used when a chapter has no front matter
default_image       = "https://iambrainstorming.vercel.app/images/og_image.jpg"
default_description = "Brainstorming ideas, exploring possibilities, and connecting thoughts into something meaningful. A space for innovation, creativity, politics, discussion, and building new perspectives."



[output.html]
mathjax-support = true
git-repository-url = "https://github.com/iambrainstorming/iambrainstorming.github.io"
